<a href="https://colab.research.google.com/github/maria2021831011/machine_learning/blob/main/4_7_handling_imbalanced_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv('/content/Credit.csv')
data.head()

,Unnamed: 0,Income,Limit,Rating,Cards,Age,Education,Gender,Student,Married,Ethnicity,Balance
0,1,14.891,3606,283,2,34,11,Male,No,Yes,Caucasian,333
1,2,106.025,6645,483,3,82,15,Female,Yes,Yes,Asian,903
2,3,104.593,7075,514,4,71,11,Male,No,No,Asian,580
3,4,148.924,9504,681,3,36,11,Female,No,No,Asian,964
4,5,55.882,4897,357,2,68,16,Male,No,Yes,Caucasian,331

In [3]:
data.tail()

,Unnamed: 0,Income,Limit,Rating,Cards,Age,Education,Gender,Student,Married,Ethnicity,Balance
395,396,12.096,4100,307,3,32,13,Male,No,Yes,Caucasian,560
396,397,13.364,3838,296,5,65,17,Male,No,No,African American,480
397,398,57.872,4171,321,5,67,12,Female,No,Yes,Caucasian,138
398,399,37.728,2525,192,1,44,13,Male,No,Yes,Caucasian,0
399,400,18.701,5524,415,5,64,7,Female,No,No,Asian,966

In [5]:
#distribution of the two classes
data['Student'].value_counts()

Student
No     360
Yes     40
Name: count, dtype: int64

In [7]:
#separating student and non student
student=data[data['Student']=='Yes']
non_student=data[data['Student']=='No']
print(student.shape)
print(non_student.shape)

(40, 12)
(360, 12)

In [15]:
#under sample create equal distribution
student_sample=non_student.sample(n=40)
print(student_sample.shape)

(40, 12)

In [16]:
#concate the two dataframe
new_data=pd.concat([student_sample,student] ,axis=0)
new_data.head()

,Unnamed: 0,Income,Limit,Rating,Cards,Age,Education,Gender,Student,Married,Ethnicity,Balance
360,361,53.566,5891,434,4,82,10,Female,No,No,Caucasian,712
352,353,104.483,7140,507,2,41,14,Male,No,Yes,African American,583
219,220,38.954,5222,370,4,76,13,Female,No,No,Caucasian,653
77,78,20.936,3254,253,1,30,15,Female,No,No,Asian,145
375,376,20.974,5673,413,5,44,16,Female,No,Yes,Caucasian,1000

In [17]:
new_data['Student'].value_counts()

Student
No     40
Yes    40
Name: count, dtype: int64